# Generated by Django 4.1.1 on 2022-09-23 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tozihat', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='img/')),
                ('price', models.CharField(max_length=30)),
                ('zaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('موجود', 'Mojood'), ('ناموجود', 'NaMojood'), ('به زودی...', 'BaZoodi')], max_length=50)),
            ],
        ),
    ]
